name: Setup

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Solc
      run: npm install -g solc@0.7.1
      shell: bash
