name: Benchmark

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Benchmark Deployment
        run: yarn workspace @balancer-labs/v2-benchmarks measure-deployment
      - name: Benchmark Single Pair
        run: yarn workspace @balancer-labs/v2-benchmarks measure-single-pair
      - name: Benchmark Multihop
        run: yarn workspace @balancer-labs/v2-benchmarks measure-multihop
      - name: Benchmark Join/Exit
        run: yarn workspace @balancer-labs/v2-benchmarks measure-join-exit
      - name: Benchmark Balancer Relayer - multicall
        run: yarn workspace @balancer-labs/v2-benchmarks measure-relayer

env:
  CI: true
